events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events' # namespace-ul pentru url-uri

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.EventView.as_view(), name='detail'),
    url(r'^add$', views.add_event, name='add'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^search', views.search, name='search'),
]

hackathon/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('events.urls'))
    
]

events/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone

# Create your models here.


class Host(models.Model):
    # mode l pentru gazde de evenimente
    user = models.OneToOneField(User, on_delete=models.CASCADE) # relationare 
    name =  models.CharField(max_length=50)


class Event(models.Model):
    CATEGORIES ={
        'pa': 'Party',
        'fo': 'Gastronomie',
        'sp': 'Sport',
        'ed': 'Educativ',
        're': 'Religios',
        'ba': 'Bautura',
        'mu': 'Muzical',
        'fi': 'Film',
    }

    title = models.CharField(max_length=50)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True) # e null daca sepecifica numai data de inceput
    description = models.CharField(max_length=256)
    likes = models.IntegerField(default=0)
    category = models.CharField(max_length=2,
                                 choices=CATEGORIES.items())
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    is_event = models.BooleanField(default=True)
    map_url = models.URLField(null=True)

    def is_upcoming(self):
        return (self.start_date >= timezone.now() and 
            self.start_date <= timezone.now() + datetime.timedelta(days=2))

    def has_not_ended(self):
        return self.end_date >= timezone.now()
    has_not_ended.boolean = True


def search_events(keyword=None, from_date=None, category=None, 
    is_offer=False, sort_criteria=None):
    queryset = Event.objects.filter(end_date__gt=timezone.now())
    if keyword is not None:
        queryset = queryset.filter(models.Q(description__contains=keyword) | 
            models.Q(title__contains=keyword) | models.Q(category__exact=keyword))
    if from_date is not None:
        queryset = queryset.filter(end_date__gt=from_date)
    if category != '':
        queryset = queryset.filter(category__exact=category)
   
    if is_offer:
        queryset = queryset.filter(is_event=False)
    if sort_criteria is not None:
        if sort_criteria == 'dhl':
            queryset = queryset.order_by('-start_date')
        elif sort_criteria == 'dlh':
            queryset = queryset.order_by('start_date')
    return queryset

events/forms.py
from django import forms
from django.core import validators
from django.utils import timezone

from .models import Event


class EventForm(forms.Form):
    error_messages={'required': 'Campul trebuie completat!',
        'invalid': 'Date invalide'}

    title = forms.CharField(label='Titlu', max_length=50)

    description = forms.CharField(label='Descriere', max_length=256,
        widget=forms.Textarea(attrs = {'rows': 3} ),
        error_messages={'required': 'Trebuie scrisa o descriere!',
                        'invalid': 'Introduceti o descriere valida!'})

    start_date = forms.DateTimeField(label='Data de inceput(optional)', 
        widget=forms.TextInput(attrs={'placeholder': 'aaaa-ll-zz [hh:mm]'}),
        error_messages={'required': 'Trebuie scrisa o data!',
                        'invalid': 'Introduceti o data valida!'})

    end_date = forms.DateTimeField(label='Data de sfarsit', 
        widget=forms.TextInput(attrs={'placeholder': 'aaaa-ll-zz [hh:mm]'}), required=False,
        error_messages={'required': 'Trebuie scrisa o data!',
                        'invalid': 'Introduceti o data valida!'})

    category = forms.ChoiceField(label='Categorie',
        choices=Event.CATEGORIES.items(), 
        error_messages={'required': 'Trebuie data o categorie!',
                        'invalid_choice': 'Introduceti o categorie valida!'})

    is_event = forms.BooleanField(label='Eveniment(oferta daca nu)',
        initial=True,
        error_messages={'required': 'Trebuie specificat!',
                        'invalid': 'True sau False!'})

    map_url = forms.URLField(label='Url locatie(Google Maps)', required=False,
        error_messages={'invalid': 'Invalid location'})

SEARCH_CRITERIAS = {
    'dhl' : 'Data(De la mare la mic)',
    'dlh' : 'Data(De la mic la mare)',

}

class SearchForm(forms.Form):
    keyword = forms.CharField(label='Cautare', max_length=50, required=False)
    from_date = forms.DateTimeField(label='Incepe dupa', required=False,
        widget=forms.TextInput(attrs={'placeholder': 'aaaa-ll-zz [hh:mm]'}),
        error_messages={'required': 'Trebuie scrisa o data!',
                        'invalid': 'Introduceti o data valida!'})
    category = forms.ChoiceField(label='Categorie', required=False,
        choices=([('', 'All')] + list(Event.CATEGORIES.items())), initial='', 
        error_messages={'required': 'Trebuie data o categorie!',
                        'invalid': 'Introduceti o categorie valida!'})
    is_offer = forms.BooleanField(label='Doar oferte', required=False,
        error_messages={'required': 'Trebuie specificat!',
                        'invalid': 'True sau False!'})
    sort_criteria = forms.ChoiceField(label='Storta dupa', required=False,
        choices=([('', 'Nimic')] + list(SEARCH_CRITERIAS.items())), 
        error_messages={'invalid_choice': 'Introduceti un criteriu valid!'})

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout, login

from .models import Event, Host, search_events
from .forms import EventForm, SearchForm
# Create your views here.

class IndexView(generic.View):
    max_on_page = 5

    def _get_popular_events(self):
        events = []
        for event in Event.objects.order_by('-likes'):
            if event.has_not_ended():
                events.append(event)
            if len(events) == self.max_on_page:
                return events
        return events

    def _get_upcoming_events(self):
        events = []
        for event in Event.objects.order_by('start_date'):
            if event.has_not_ended() and event.is_upcoming():
                events.append(event)
            if len(events) == self.max_on_page:
                return events
        return events

    def _get_list(self, list_type):
        if list_type == 'upcoming':
            return self._get_upcoming_events()
        elif list_type == 'popular':
            return self._get_popular_events()
            
    def get(self, request):
        context = {}
        list_type = 'popular'
        if 'upcoming' in request.GET:
            list_type = 'upcoming'

        context['event_list'] = self._get_list(list_type)
        context['list_type'] = list_type
        return render(request, 'events/index.html', context)


class EventView(generic.DetailView):
    model = Event
    template_name = 'events/detail.html'


@login_required
def add_event(request):
    form = EventForm(request.POST)
    
    if request.method == "POST":
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            category = form.cleaned_data['category']
            is_event = form.cleaned_data['is_event']
            map_url = form.cleaned_data['map_url']

            new_event = Event(title=title, description=description, 
                start_date=start_date, end_date=end_date, host=request.user,
                category=category, map_url=map_url)

            new_event.save()
            messages.add_message(request, messages.SUCCESS, 'Eveniment adaugat cu success!')
            return redirect('events:detail', pk=new_event.id)
    else:
        form = EventForm()
    return render(request, 'events/add.html', {'form': form})


def search(request):
    form = SearchForm(request.GET, initial={'is_event': True})
    event_list = []
    if form.is_valid():
        keyword = form.cleaned_data['keyword']
        is_offer = form.cleaned_data['is_offer']
        from_date = form.cleaned_data['from_date']
        category = form.cleaned_data['category']
        sort_criteria = form.cleaned_data['sort_criteria']

        event_list = search_events(keyword=keyword, is_offer=is_offer, 
            from_date=from_date, category=category, sort_criteria=sort_criteria)
    return render(request, 'events/search.html', {'form': form, 'event_list': event_list})

@login_required
def logout(request):
    logout(request)
    # Redirect to a success page.


class SearchView(generic.ListView):
    template_name = 'events/search.html'
    context_object_name = 'event_list'

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        if form.is_valid():
            pass
        else:
            return None

events/templates/events/add.html
{% extends 'events/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Adaugare eveniment
{% endblock %}

{% block content %}

    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='Submit' reset="Cancel" %}{% endbuttons %}
    </form>

{% endblock %}

events/templates/events/base.html
{% extends 'events/bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}

 <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'events:index' %}">EvRo - Event Rounder</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" action="{% url 'events:search' %}" method="get">
            <div class="form-group">
              <input type="text" name="keyword" placeholder="Search" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Search</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>


    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>

        {% bootstrap_messages %}

        {% block content %}(no content){% endblock %}

        <hr>

        <footer>
            <p>&copy; 2015 - Hermes Hackathon - Niki & Co. </p>
        </footer>

    </div>


{% endblock %}

events/templates/events/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

events/templates/events/detail.html
{% extends 'events/base.html' %}

{% load bootstrap3 %}

{% block title %}
    {{ event.title }}
{% endblock %}

{% block content %}

<div class="row" style="margin-bottom: 10px">
    <p class="col-md-10"><b>{{ event.start_date|date:"D. d N Y H:i" }} to {{ event.end_date|date:"D. d N Y H:i" }}</b></p>

{% if event.map_url %}
    <a class="col-md-2" style="text-align: right" href= {{event.map_url}} ><button class="btn btn-success">Location</button></a>

{% endif %}
</div>

<div class="well">
    <p>{{ event.description }}</p>
    <p>Category: {{ event.get_category_display }}</p>
    <p>Likes: {{ event.likes }} </p>
</div>

{% endblock %}

events/templates/events/index.html
{% extends 'events/base.html' %}

{% load bootstrap3 %}

{% block title %}
    EvRo - Event Rounder
{% endblock %}

{% block content %}

<html>
    <head>
        <title>Titlu</title>
        
    </head>
    <body>
    {% if list_type == "popular" %} 
        <h2> Cele mai populare  evenimente (click aici pt <a href="{% url 'events:index' %}?upcoming">recente</a>)</h2>
    {% elif list_type == "upcoming" %}
        <h2> Cele mai recente  evenimente (click aici pt <a href="{% url 'events:index' %}">populare</a>)</h2>
    {% endif %}
    
    <div class="container">
    {% for event in event_list %}
        <div class="well">
            <a href="{% url 'events:detail' event.id %}"><h2>{{ event.title }}</h2></a>
            <p>{{ event.description|truncatechars:100 }}</p>
        </div>
    {% endfor %}
    </div>
    </body>
</html>

{% endblock %}

events/templates/events/search.html
{% extends 'events/base.html' %}

{% load bootstrap3 %}

{% block title %}
    Cautare eveniment
{% endblock %}

{% block content %}
<div class="row">
    <form class="col-md-3" role="form" method="get">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='Submit' reset="Cancel" %}{% endbuttons %}
    </form>

    <div class="container">
    <div class="col-md-8">
    {% if event_list|length != 0 %}
    {% for event in event_list %}
        <div class="well">
            <a href="{% url 'events:detail' event.id %}"><h2>{{ event.title }}</h2></a>
            <p>{{ event.description|truncatechars:100 }}</p>
        </div>
    {% endfor %}
    {% elif event_list|length == 0 %}
        <div class="col-md-4"><h2>No events match!</h2></div>
    {% endif %}
    </div>
    </div>
<div>
{% endblock %}